language: php
script: php bin/phpunit -c app/
before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer install


notifications:
    slack: phpteams:bxqLzCrk3eNzvZkrrV4g4Dvq