AppBundle\Entity\Mails:
    type: entity
    table: mails
    repositoryClass : AppBundle\Repository\MailsRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mail:
            type: string
            nullable: false
            length: 100
            fixed: false
    lifecycleCallbacks: {  }
