AppBundle\Entity\ParisFlat:
    type: entity
    table: paris_flat
    repositoryClass : AppBundle\Repository\ParisFlatRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uai:
            type: string
            nullable: false
            length: 10
            fixed: false
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
        type:
            type: integer
            nullable: false
            unsigned: false
        longitude:
            type: integer
            nullable: false
            unsigned: false
        latitude:
            type: integer
            nullable: false
            unsigned: false
        thumbnail:
            type: string
            nullable: false
            length: 255
            fixed: false
        date:
            type: integer
            nullable: false
            unsigned: false
        price:
            type: integer
            nullable: false
            unsigned: false
        album:
            type: text
            nullable: false
            length: 65535
            fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            fixed: false
        owner:
            type: string
            nullable: false
            length: 50
            fixed: false
    lifecycleCallbacks: {  }
