AppBundle\Entity\Token:
    type: entity
    table: token
#    repositoryClass : AppBundle\Repository\ParisSchoolRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        token:
            type: string
            nullable: false
            length: 10
            fixed: false
        user:
            type: integer
            nullable: false
            length: 100
            fixed: false
    lifecycleCallbacks: {  }
