AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass : AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uai:
            type: string
            nullable: false
            length: 10
            fixed: false
        nom:
            type: string
            nullable: false
            length: 100
            fixed: false
        picture:
            type: string
            nullable: false
            length: 200
            fixed: false
        pass:
            type: string
            nullable: false
            length: 200
            fixed: false
        mail:
            type: string
            nullable: false
            length: 200
            fixed: false
        number:
            type: string
            nullable: false
            lenght: 100
            unsigned: false
    lifecycleCallbacks: {  }
